// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Context;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(OvipDbContext))]
    [Migration("20260514084226_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Models.Entities.Categories.OvipCategory", b =>
                {
                    b.Property<int>("OvipCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OvipCategoryId"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("longtext");

                    b.HasKey("OvipCategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Categories.OvipCategoryConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OvipCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("OvipProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OvipCategoryId");

                    b.HasIndex("OvipProductId", "OvipCategoryId")
                        .IsUnique();

                    b.ToTable("CategoryConnections", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Manufacture.OvipManufacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoComplete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OvipProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OvipProductId")
                        .IsUnique();

                    b.ToTable("Manufactures", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Manufacture.OvipManufacturePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufactureId")
                        .HasColumnType("int");

                    b.Property<int>("PartProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ManufactureId");

                    b.HasIndex("PartProductId");

                    b.ToTable("ManufactureParts", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Parameters.OvipParameter", b =>
                {
                    b.Property<int>("OvipParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OvipParameterId"));

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("OvipParameterId");

                    b.ToTable("Parameters", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Pricing.OvipPriceList", b =>
                {
                    b.Property<int>("OvipPriceListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OvipPriceListId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("OvipPriceListId");

                    b.ToTable("PriceLists", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Pricing.OvipPriceListPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GrossPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("GrossSalePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NetSalePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("OvipPriceListId")
                        .HasColumnType("int");

                    b.Property<int>("OvipProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SaleEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SaleStart")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OvipPriceListId");

                    b.HasIndex("OvipProductId");

                    b.ToTable("PriceListPrices", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Pricing.OvipQuantityDiscount", b =>
                {
                    b.Property<int>("OvipQuantityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OvipQuantityId"));

                    b.Property<decimal>("DiscountFromQuantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("DiscountUntilQuantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("OvipProductId")
                        .HasColumnType("int");

                    b.Property<int>("PriceListId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OvipQuantityId");

                    b.HasIndex("OvipProductId");

                    b.ToTable("QuantityDiscounts", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Products.OvipProduct", b =>
                {
                    b.Property<int>("OvipProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OvipProductId"));

                    b.Property<string>("AcquisitionCostCurrency")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("AcquisitionCostExchange")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AcquisitionCostForeign")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AcquisitionCostHuf")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AltUnit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("AltUnitQuantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("GrossPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("GrossSalePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("GrossWeight")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LongDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("ManufactureSku")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NetSalePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("NetWeight")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Orderable")
                        .HasColumnType("int");

                    b.Property<int>("OvipCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProductUnitQuantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SaleEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SaleStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("WebshopVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("Width")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("OvipProductId");

                    b.HasIndex("OvipCategoryId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Products.OvipProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("MainImage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OvipProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailImage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("OvipProductId");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Products.OvipProductParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OvipParameterId")
                        .HasColumnType("int");

                    b.Property<int>("OvipParameterValueId")
                        .HasColumnType("int");

                    b.Property<int>("OvipProductId")
                        .HasColumnType("int");

                    b.Property<string>("ParameterValue")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("OvipParameterId");

                    b.HasIndex("OvipProductId");

                    b.ToTable("ProductParameters", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Products.OvipStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FreeStock")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("OvipProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OvipProductId")
                        .IsUnique();

                    b.ToTable("Stocks", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Categories.OvipCategory", b =>
                {
                    b.HasOne("Models.Entities.Categories.OvipCategory", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Models.Entities.Categories.OvipCategoryConnection", b =>
                {
                    b.HasOne("Models.Entities.Categories.OvipCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("OvipCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Products.OvipProduct", "Product")
                        .WithMany("Categories")
                        .HasForeignKey("OvipProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Models.Entities.Manufacture.OvipManufacture", b =>
                {
                    b.HasOne("Models.Entities.Products.OvipProduct", "Product")
                        .WithOne("Manufacture")
                        .HasForeignKey("Models.Entities.Manufacture.OvipManufacture", "OvipProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Models.Entities.Manufacture.OvipManufacturePart", b =>
                {
                    b.HasOne("Models.Entities.Manufacture.OvipManufacture", "Manufacture")
                        .WithMany("Parts")
                        .HasForeignKey("ManufactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Products.OvipProduct", "PartProduct")
                        .WithMany()
                        .HasForeignKey("PartProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Manufacture");

                    b.Navigation("PartProduct");
                });

            modelBuilder.Entity("Models.Entities.Pricing.OvipPriceListPrice", b =>
                {
                    b.HasOne("Models.Entities.Pricing.OvipPriceList", "PriceList")
                        .WithMany("Prices")
                        .HasForeignKey("OvipPriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Products.OvipProduct", "Product")
                        .WithMany("PricelistPrices")
                        .HasForeignKey("OvipProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Models.Entities.Pricing.OvipQuantityDiscount", b =>
                {
                    b.HasOne("Models.Entities.Products.OvipProduct", null)
                        .WithMany("QuantityDiscounts")
                        .HasForeignKey("OvipProductId");
                });

            modelBuilder.Entity("Models.Entities.Products.OvipProduct", b =>
                {
                    b.HasOne("Models.Entities.Categories.OvipCategory", "MainCategory")
                        .WithMany()
                        .HasForeignKey("OvipCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Products.OvipProduct", "VariantProduct")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MainCategory");

                    b.Navigation("VariantProduct");
                });

            modelBuilder.Entity("Models.Entities.Products.OvipProductImage", b =>
                {
                    b.HasOne("Models.Entities.Products.OvipProduct", "Product")
                        .WithMany("Images")
                        .HasForeignKey("OvipProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Models.Entities.Products.OvipProductParameter", b =>
                {
                    b.HasOne("Models.Entities.Parameters.OvipParameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("OvipParameterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Products.OvipProduct", "Product")
                        .WithMany("Parameters")
                        .HasForeignKey("OvipProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameter");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Models.Entities.Products.OvipStock", b =>
                {
                    b.HasOne("Models.Entities.Products.OvipProduct", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("Models.Entities.Products.OvipStock", "OvipProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Models.Entities.Categories.OvipCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Models.Entities.Manufacture.OvipManufacture", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Models.Entities.Pricing.OvipPriceList", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Models.Entities.Products.OvipProduct", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Images");

                    b.Navigation("Manufacture");

                    b.Navigation("Parameters");

                    b.Navigation("PricelistPrices");

                    b.Navigation("QuantityDiscounts");

                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
