version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: OVIP_Seged_Raktarkezelo/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080

      # EF Core / DB connection (matches ConnectionStrings:DefaultConnection)
      ConnectionStrings__DefaultConnection: Server=72.60.176.243;Port=3306;Database=OVIP_Seged_Raktarkezelo;User=root;Password=password

    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: OVIP_Seged_Raktarkezelo
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: